export {default as AdminLayout} from './AdminLayout'
// export {default as Dashboard} from './Dashboard'
export {default as ManageOrder} from './ManageOrder'
export {default as ManageProducts} from './ManageProducts'
export {default as Manageuser} from './Manageuser'
export {default as CreateProducts} from './CreateProducts'
export {default as Updateproducts} from './Updateproducts'